language: php
php:
  - 7.0
  - 7.1

before_script:
  - composer selfupdate
  - composer install --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpspec run -fpretty
